### PR TITLE
Backend code

### PR DESCRIPTION
**Pull request by rishabhbhardwaj**

### CODE REVIEW

**Comment by shivendrasoni** [comment]
You should indent code better.

Also, your variable naming convention is a bit off.

**Comment by rishabhbhardwaj** [comment]
@shivendrasoni f*** you.. i deserve 🥇

**Comment by shivendrasoni** [comment]
LGTM 👍

**Comment by rishabhbhardwaj** [comment]
@shivendrasoni After merging 😮

**Pull request merged**
